export const CREATE_BRAND = 'CREATE_BRAND';
export const CREATE_BRAND_REQUESTED = 'CREATE_BRAND_REQUESTED';

export const GET_BRAND = 'GET_BRAND'
export const GET_BRAND_REQUESTED = 'GET_BRAND_REQUESTED';

export const UPDATE_BRAND = 'UPDATE_BRAND';
export const UPDATE_BRAND_REQUESTED = 'UPDATE_BRAND_REQUESTED';

export const DELETE_BRAND = 'DELETE_BRAND';
export const DELETE_BRAND_REQUESTED = 'DELETE_BRAND_REQUESTED';

export const GET_BRANDS = 'GET_BRANDS';
export const GET_BRANDS_REQUESTED = 'GET_BRANDS_REQUESTED';

export const ERROR = 'ERROR'
export const LOADING = 'LOADING'
export const SUCCESS = 'SUCCESS'
export const INIT_STATUS = 'INIT_STATUS'