export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CREATE_CATEGORY_REQUESTED = 'CREATE_CATEGORY_REQUESTED';

export const GET_CATEGORY = 'GET_CATEGORY'
export const GET_CATEGORY_REQUESTED = 'GET_CATEGORY_REQUESTED';

export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const UPDATE_CATEGORY_REQUESTED = 'UPDATE_CATEGORY_REQUESTED';

export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const DELETE_CATEGORY_REQUESTED = 'DELETE_CATEGORY_REQUESTED';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_REQUESTED = 'GET_CATEGORIES_REQUESTED';

export const ERROR = 'ERROR'
export const LOADING = 'LOADING'
export const SUCCESS = 'SUCCESS'
export const INIT_STATUS = 'INIT_STATUS'