export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const CREATE_PRODUCT_REQUESTED = 'CREATE_PRODUCT_REQUESTED';

export const GET_PRODUCT = 'GET_PRODUCT'
export const GET_PRODUCT_REQUESTED = 'GET_PRODUCT_REQUESTED';

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const UPDATE_PRODUCT_REQUESTED = 'UPDATE_PRODUCT_REQUESTED';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_REQUESTED = 'DELETE_PRODUCT_REQUESTED';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_REQUESTED = 'GET_PRODUCTS_REQUESTED';

export const GET_RELATED_PRODUCTS = 'GET_RELATED_PRODUCTS'
export const GET_RELATED_PRODUCTS_REQUESTED = 'GET_RELATED_PRODUCTS_REQUESTED'

export const ERROR = 'ERROR'
export const LOADING = 'LOADING'
export const SUCCESS = 'SUCCESS'
export const INIT_STATUS = 'INIT_STATUS'
export const SET_KEYWORD = 'SET_KEYWORD'